
- name: disable default nodejs
  ansible.builtin.command: dnf module disable nodejs -y 

- name: enable nodejs 20
  ansible.builtin.command: dnf module enable nodejs:20 -y

- name: install nodejs
  ansible.builtin.package:
    name: nodejs
    state: present
  
- name: Creating user
  ansible.builtin.user:
    name: expense

- name: Creating dircetory
  ansible.builtin.file:
    path: /app
    state: directory

- name: Download expense application
  ansible.builtin.get_url:
    url: https://expense-joindevops.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
    dest: /tmp/backend.zip

- name: extract backend application
  ansible.builtin.unarchive:
    src: /tmp/backend.zip
    dest: /app
    remote_src: yes

- name: Install node dependencies
  community.general.npm:
    name: npm
    path: /app

- name: Copy backend services
  ansible.builtin.copy:
    src: backend.services.j2
    dest: /etc/systemd/system/backend.service

