
- name: disable default nodejs
  ansible.builtin.command: dnf module disable nodejs -y 

- name: enable nodejs 20
  ansible.builtin.command: dnf module enable nodejs:20 -y

- name: install nodejs
  ansible.builtin.package:
    name: nodejs
    state: present

- name: install mysql python libraries
  ansible.builtin.pip:
    executable: pip3.9
    name: "{{ item }}"
  loop:
  - cryptography
  - PyMySQL
  
- name: Creating user
  ansible.builtin.user:
    name: expense

- name: remove dircetory
  ansible.builtin.file:
    path: /app
    state: absent

- name: Creating dircetory
  ansible.builtin.file:
    path: /app
    state: directory
  
- name: Delete backend file
  ansible.builtin.file:
    path: /tmp/backend.zip
    state: absent

- name: Download backend application
  ansible.builtin.get_url:
    url: https://expense-joindevops.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
    dest: /tmp/backend.zip

- name: extract backend application
  ansible.builtin.unarchive:
    src: /tmp/backend.zip
    dest: /app
    remote_src: yes

- name: Install node dependencies
  community.general.npm:
    path: /app

- name: Copy backend services
  ansible.builtin.template:
    src: backend.service.j2
    dest: /etc/systemd/system/backend.service
  notify: daemon reload

- name: start and enable services
  ansible.builtin.service:
    name: backend
    state: started
    enabled: yes

- name: install mysql
  ansible.builtin.package:
    name: mysql
    state: present

- name: loading mysql data into backend
  community.mysql.mysql_db:
    state: import
    name: all
    login_host: "{{ MYSQL_HOST }}"
    login_user: "{{ MYSQL_ROOT_USER }}"
    login_password: "{{ MYSQL_ROOT_PASSWORD }}"
    target: /app/schema/backend.sql

- name: Restart backend
  ansible.builtin.service:
    name: backend
    state: restarted

   