
- name: install nginx
  ansible.builtin.package:
    name : nginx
    state: present

- name: start and enable nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes

- name: remove default dircetory
  ansible.builtin.file:
    path: /usr/share/nginx/html/*
    state: absent

- name: create dircetory
  ansible.builtin.file:
    path: /usr/share/nginx/html/
    state: directory

  ansible.builtin.get_url:
    url: https://expense-joindevops.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
    dest: /tmp/frontend.zip

- name: extract frontend application
  ansible.builtin.unarchive:
    src: /tmp/frontend.zip
    dest: /usr/share/nginx/html/
    remote_src: yes

- name: creating reverse proxy
  ansible.builtin.copy:
    src: expense.conf
    dest: /etc/nginx/default.d/expense.conf

- name: restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted