
- name: install nginx
  ansible.builtin.package:
    name : nginx
    state: present

  
- name: remove html directory
  ansible.builtin.file:
    state: absent
    path: /usr/share/nginx/html/

- name: create html directory
  ansible.builtin.file:
    path: /usr/share/nginx/html/
    state: directory

- name: download frontend code
  ansible.builtin.get_url:
    url: https://expense-joindevops.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
    dest: /tmp/frontend.zip

- name: extract frontend application
  ansible.builtin.unarchive:
    src: /tmp/frontend.zip
    dest: /usr/share/nginx/html/
    remote_src: yes

- name: creating reverse proxy
  ansible.builtin.copy:
    src: expense.conf
    dest: /etc/nginx/default.d/expense.conf

- name: start and enable nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes

- name: restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted